version: '3.3'

services:
  news_aggregator:
    image: kudryashovroman/mongodb-redis:latest
    container_name: news_aggregator_test
    restart: 'no'
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://$MONGODB_USERNAME:$MONGODB_PASSWORD@mongodb:27017
      RUST_LOG: debug
      ENABLE_WRITING_HANDLERS: 'false'
    ports:
      - '9000:9000'

  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: 'no'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: news_aggregator_test
    ports:
      - '27017:27017'

  mongodb-seed:
    image: mongo:5
    container_name: mongodb-seed
    depends_on:
      - mongodb
    volumes:
      - ./mongodb-init:/mongodb-init
    links:
      - mongodb
    command:
      mongoimport --host mongodb --db news_aggregator_test --collection sources --authenticationDatabase admin --username $MONGODB_USERNAME --password $MONGODB_PASSWORD --drop --jsonArray --file /mongodb-init/init_sources.json
      mongoimport --host mongodb --db news_aggregator_test --collection articles --authenticationDatabase admin --username $MONGODB_USERNAME --password $MONGODB_PASSWORD --jsonArray --file /mongodb-init/init_articles.json